### ISSUE TITLE
CLIENT_EVENTS.session.proposal not received

### ISSUE THREAD

**Issue by RobertoSnap** [WalletConnect-Labs/walletconnect-v2-monorepo#56]
Did some testing in React. Running 2.0.0-aplha.35

Server running from `make dev``

To reproduce:

1. https://github.com/RobertoSnap/wallet-connect-react-test
2. Run yarn
3. Run yarn start
4. Run yarn test

Also tested with a separate client, same thing here CLIENT_EVENTS.session.proposal is not received.

https://github.com/RobertoSnap/wc-wallet-demo-hack (you probably don't need to set this up).

Output from test (logs both clients)
```bash
[2021-04-14 23:50:39.823 +0200] INFO: Client Initilization Success
    context: "client"
[2021-04-14 23:50:39.837 +0200] INFO: Client Initilization Success
    context: "client"
[2021-04-14 23:50:39.865 +0200] INFO: Outgoing Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.869 +0200] INFO: Incoming Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.869 +0200] INFO: Emitting subscription_created
    context: "client/pairing/pending"
[2021-04-14 23:50:39.870 +0200] INFO: Emitting pairing_proposed
    context: "client/pairing"
[2021-04-14 23:50:39.870 +0200] INFO: Emitting pairing_proposal
    context: "client"
[2021-04-14 23:50:39.911 +0200] INFO: Outgoing Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.912 +0200] INFO: Incoming Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.913 +0200] INFO: Emitting subscription_created
    context: "client/pairing/settled"
[2021-04-14 23:50:39.913 +0200] INFO: Emitting pairing_settled
    context: "client/pairing"
[2021-04-14 23:50:39.913 +0200] INFO: Emitting pairing_created
    context: "client"
[2021-04-14 23:50:39.914 +0200] INFO: Outgoing Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.914 +0200] INFO: Emitting subscription_updated
    context: "client/pairing/settled"
[2021-04-14 23:50:39.914 +0200] INFO: Emitting pairing_updated
    context: "client/pairing"
[2021-04-14 23:50:39.914 +0200] INFO: Emitting pairing_updated
    context: "client"
[2021-04-14 23:50:39.916 +0200] INFO: Outgoing Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.918 +0200] INFO: Incoming Relay Payload
    context: "client/relayer"
[2021-04-14 23:50:39.918 +0200] INFO: Emitting subscription_created
    context: "client/pairing/pending"
[2021-04-14 23:50:39.918 +0200] INFO: Emitting pairing_responded
    context: "client/pairing"
[2021-04-14 23:50:39.919 +0200] INFO: Outgoing Relay Payload
    context: "client/relayer"
 PASS  src/components/WalletConnect.test.tsx
  ● Console

    console.log
      Mobile listening

      at src/utils/WalletClient.ts:51:15

    console.log
      dAPP listening

      at src/utils/WalletConnectWeb3Provider.ts:78:15

    console.log
      enable - create session

      at WalletConnectWeb3Provider.enable (src/utils/WalletConnectWeb3Provider.ts:108:13)

    console.log
      CLIENT_EVENTS.pairing.proposal

      at EventEmitter.<anonymous> (src/utils/WalletConnectWeb3Provider.ts:82:19)

    console.log
      Start pair

      at WalletClient.pair (src/utils/WalletClient.ts:44:13)
```

Server log:
```bash
[nodemon] [2021-04-14 23:39:35.055 +0200] INFO: incoming request
[nodemon]     req: {
[nodemon]       "method": "GET",
[nodemon]       "url": "/?env=node&protocol=wc&version=2",
[nodemon]       "hostname": "0.0.0.0:5555",
[nodemon]       "remoteAddress": "127.0.0.1",
[nodemon]       "remotePort": 61931
[nodemon]     }
[nodemon]     reqId: "req-g"
[nodemon] [2021-04-14 23:39:35.056 +0200] INFO: New Socket Connected
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.056 +0200] DEBUG:
[nodemon]     type: "event"
[nodemon]     event: "connection"
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.079 +0200] INFO: incoming request
[nodemon]     req: {
[nodemon]       "method": "GET",
[nodemon]       "url": "/?env=node&protocol=wc&version=2",
[nodemon]       "hostname": "0.0.0.0:5555",
[nodemon]       "remoteAddress": "127.0.0.1",
[nodemon]       "remotePort": 61932
[nodemon]     }
[nodemon]     reqId: "req-h"
[nodemon] [2021-04-14 23:39:35.079 +0200] INFO: New Socket Connected
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.079 +0200] DEBUG:
[nodemon]     type: "event"
[nodemon]     event: "connection"
[nodemon]     socketId: "e8b4f5ba4b5e93e22c33c2e73eb757bb3e106544280c90322d3a9235c3867202"
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.122 +0200] DEBUG: Incoming Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.122 +0200] INFO: Incoming JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.122 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "incoming"
[nodemon]     payload: {
[nodemon]       "id": 1618436375120246,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "method": "waku_subscribe",
[nodemon]       "params": {
[nodemon]         "topic": "a478fe1cae4083209c533887a2334e58900ff4a37fa387cb0cea2b3b88efb1d4"
[nodemon]       }
[nodemon]     }
[nodemon]     socketId: "e8b4f5ba4b5e93e22c33c2e73eb757bb3e106544280c90322d3a9235c3867202"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.122 +0200] DEBUG: Subscribe Request Received
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.122 +0200] DEBUG: Setting Subscription
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.123 +0200] DEBUG: Outgoing Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.123 +0200] INFO: Outgoing JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.123 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "outgoing"
[nodemon]     payload: {
[nodemon]       "id": 1618436375120246,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "result": "6211c27cc8f6cc63a6d5fb3ad89c7ac9cd672a602831623b7960a480f29e9484"
[nodemon]     }
[nodemon]     socketId: "e8b4f5ba4b5e93e22c33c2e73eb757bb3e106544280c90322d3a9235c3867202"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.123 +0200] DEBUG: Pushing Cached Messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.123 +0200] DEBUG: Getting Message
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.126 +0200] DEBUG: Found 0 cached messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.180 +0200] DEBUG: Incoming Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.180 +0200] INFO: Incoming JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.180 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "incoming"
[nodemon]     payload: {
[nodemon]       "id": 1618436375179026,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "method": "waku_subscribe",
[nodemon]       "params": {
[nodemon]         "topic": "d69922b963dfeb863a2824c9a00b72728042662bf6ac55dec6f728e7cd5351e8"
[nodemon]       }
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.180 +0200] DEBUG: Subscribe Request Received
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.180 +0200] DEBUG: Setting Subscription
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.181 +0200] DEBUG: Outgoing Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.181 +0200] INFO: Outgoing JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.181 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "outgoing"
[nodemon]     payload: {
[nodemon]       "id": 1618436375179026,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "result": "fb36b7b396cc8cfc255b5b06da4aa74af5621b3107700fdf5fc1eb1867de6532"
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.181 +0200] DEBUG: Pushing Cached Messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.181 +0200] DEBUG: Getting Message
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.187 +0200] DEBUG: Incoming Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.188 +0200] INFO: Incoming JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.188 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "incoming"
[nodemon]     payload: {
[nodemon]       "id": 1618436375182313,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "method": "waku_subscribe",
[nodemon]       "params": {
[nodemon]         "topic": "a478fe1cae4083209c533887a2334e58900ff4a37fa387cb0cea2b3b88efb1d4"
[nodemon]       }
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.188 +0200] DEBUG: Subscribe Request Received
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.188 +0200] DEBUG: Setting Subscription
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.188 +0200] DEBUG: Outgoing Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.188 +0200] INFO: Outgoing JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.188 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "outgoing"
[nodemon]     payload: {
[nodemon]       "id": 1618436375182313,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "result": "9ffc70e0d9280faea3bb430ab3dda7dc45a48cf873d08d133551a017c9da4cd8"
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.189 +0200] DEBUG: Incoming Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.189 +0200] INFO: Incoming JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.189 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "incoming"
[nodemon]     payload: {
[nodemon]       "id": 1618436375186932,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "method": "waku_publish",
[nodemon]       "params": {
[nodemon]         "topic": "d69922b963dfeb863a2824c9a00b72728042662bf6ac55dec6f728e7cd5351e8",
[nodemon]         "message": "05fef94ba95369337b51aec42145b087529d7215f73a49f6c82d1d9232825fee95a50334ef758d32e6259bfc99621a72e0fb3b455b0f42147302de539af8b6f6fcf3c076c0afddcd630d7f073091be6cafb5647840ef5f915a8e32691fce8b3a7efbcb691046f3bd2876246a79bf697b42d9106c4d917763b2ad3443bea6c496054d42d6a859c57979e3cc94ad34ebafb55b8e9174072b0898a4d8102fb3c23264953265035f5de5de15888606fa54d9d9fab2a5df7e25b94c204d4ac9de2bac7c5239bd09eefa03c1bc255f4f44c73f8afe5cfa5621b2e8291fb75f8516cf96a7c710a3b884667492bfa3ae595e6d4989a8c1f3e03402a42eed8003d25c1692",
[nodemon]         "ttl": 21600
[nodemon]       }
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.189 +0200] DEBUG: Publish Request Received
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.189 +0200] DEBUG: Pushing Cached Messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.189 +0200] DEBUG: Getting Message
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.190 +0200] DEBUG: Found 0 cached messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.192 +0200] DEBUG: Incoming Socket Message
[nodemon]     context: "server/websocket"
[nodemon] [2021-04-14 23:39:35.192 +0200] INFO: Incoming JSON-RPC Payload
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.192 +0200] DEBUG:
[nodemon]     type: "payload"
[nodemon]     direction: "incoming"
[nodemon]     payload: {
[nodemon]       "id": 1618436375190178,
[nodemon]       "jsonrpc": "2.0",
[nodemon]       "method": "waku_publish",
[nodemon]       "params": {
[nodemon]         "topic": "a478fe1cae4083209c533887a2334e58900ff4a37fa387cb0cea2b3b88efb1d4",
[nodemon]         "message": "7b226964223a313631383433363337353139303635382c226a736f6e727063223a22322e30222c226d6574686f64223a2277635f70616972696e67417070726f7665222c22706172616d73223a7b22746f706963223a2264363939323262393633646665623836336132383234633961303062373237323830343236363262663661633535646563366637323865376364353335316538222c2272656c6179223a7b2270726f746f636f6c223a2277616b75227d2c22726573706f6e646572223a7b227075626c69634b6579223a2235323964373231356637336134396636633832643164393233323832356665653935613530333334656637353864333265363235396266633939363231613732227d2c22657870697279223a313632303235303737353136332c227374617465223a7b7d7d7d",
[nodemon]         "ttl": 21600
[nodemon]       }
[nodemon]     }
[nodemon]     socketId: "4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4"
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.192 +0200] DEBUG: Publish Request Received
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.199 +0200] DEBUG: Getting Notification
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.199 +0200] DEBUG: Getting Notification
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.200 +0200] DEBUG: Found 0 cached messages
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.200 +0200] DEBUG: Setting Message
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.201 +0200] DEBUG: Setting Message
[nodemon]     context: "server/redis"
[nodemon] [2021-04-14 23:39:35.212 +0200] DEBUG: Removing Socket Subscriptions
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.212 +0200] DEBUG: Removing Socket Subscriptions
[nodemon]     context: "server/websocket/legacy/subscription"
[nodemon] [2021-04-14 23:39:35.213 +0200] DEBUG: Removing Socket Subscriptions
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.213 +0200] DEBUG: Removing Socket Subscriptions
[nodemon]     context: "server/websocket/legacy/subscription"
[nodemon] [2021-04-14 23:39:35.225 +0200] DEBUG: Searching subscriptions
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.226 +0200] DEBUG: Getting Subscriptions
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.226 +0200] DEBUG: Found 0 subscriptions
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.226 +0200] DEBUG: Searching subscriptions
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] [2021-04-14 23:39:35.226 +0200] DEBUG: Getting Subscriptions
[nodemon]     context: "server/websocket/jsonrpc/subscription"
[nodemon] [2021-04-14 23:39:35.226 +0200] DEBUG: Found 0 subscriptions
[nodemon]     context: "server/websocket/jsonrpc"
[nodemon] (node:76409) UnhandledPromiseRejectionWarning: Error: Socket not active with socketId: 4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4
[nodemon]     at WebSocketService.send (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/ws.js:73:19)
[nodemon]     at JsonRpcService.<anonymous> (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:180:25)
[nodemon]     at Generator.next (<anonymous>)
[nodemon]     at /Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:8:71
[nodemon]     at new Promise (<anonymous>)
[nodemon]     at __awaiter (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:4:12)
[nodemon]     at JsonRpcService.socketSend (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:178:16)
[nodemon]     at JsonRpcService.<anonymous> (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:107:18)
[nodemon]     at Generator.next (<anonymous>)
[nodemon]     at fulfilled (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:5:58)
[nodemon] (node:76409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
[nodemon] (node:76409) UnhandledPromiseRejectionWarning: Error: Socket not active with socketId: 4d75270e9b31516d03dfd2d7d2dfa26ae6282280c3454d418e6427669c0627a4
[nodemon]     at WebSocketService.send (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/ws.js:73:19)
[nodemon]     at JsonRpcService.<anonymous> (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:180:25)
[nodemon]     at Generator.next (<anonymous>)
[nodemon]     at /Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:8:71
[nodemon]     at new Promise (<anonymous>)
[nodemon]     at __awaiter (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:4:12)
[nodemon]     at JsonRpcService.socketSend (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:178:16)
[nodemon]     at JsonRpcService.<anonymous> (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:107:18)
[nodemon]     at Generator.next (<anonymous>)
[nodemon]     at fulfilled (/Users/robin/code/walletconnect-v2-monorepo/servers/relay/dist/jsonrpc.js:5:58)
[nodemon] (node:76409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
```

**Comment by RobertoSnap** [comment]
Tested with /examples/react-wallet, got the correct result. I have done something wrong, so will find it in there.
